# Generated by Django 3.2.7 on 2022-03-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_name', models.CharField(max_length=100)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('rental_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('equipment_descriptions', models.CharField(max_length=250)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'equipment_db',
                'ordering': ['equipment_name'],
            },
        ),
    ]
