# Generated by Django 3.2.7 on 2022-04-22 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_name', models.CharField(max_length=100)),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('rental_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('equipment_descriptions', models.CharField(max_length=250)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'equipment_db',
                'ordering': ['equipment_name'],
            },
        ),
        migrations.CreateModel(
            name='inventory_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('sales_invoice', models.CharField(max_length=50, verbose_name='Inventory id')),
                ('supplier', models.CharField(max_length=100, verbose_name='Supplier')),
                ('transaction_type', models.CharField(choices=[('1', 'In'), ('2', 'Out')], max_length=10, verbose_name='Tx Type')),
                ('mrs_number', models.CharField(max_length=50, verbose_name='MRS')),
                ('requested_by', models.CharField(max_length=10, verbose_name='Requested by')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventories',
                'db_table': 'inventory',
                'ordering': ['-trans_date'],
            },
        ),
        migrations.CreateModel(
            name='inventory_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(max_length=20, verbose_name='Inventory id')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('category_inv', models.CharField(choices=[('1', 'Tires'), ('2', 'Oil & Lubricants'), ('3', 'Mechanical Parts'), ('4', 'Office Supplies'), ('5', 'Tools Supplies'), ('6', 'Others Supplies')], max_length=25, verbose_name='Category Type')),
                ('item_description', models.CharField(max_length=100, verbose_name='Item Description')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('unit_measurement', models.CharField(max_length=50, verbose_name='Unit')),
                ('inventory_price', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('inventory_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('equipment', models.CharField(max_length=20, verbose_name='equipment')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transactions_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.inventory_db')),
            ],
            options={
                'verbose_name': 'inventory_transaction',
                'verbose_name_plural': 'inventories_transactions',
                'db_table': 'inventory_transaction',
                'ordering': ['-transactions_inventory'],
            },
        ),
    ]
