# Generated by Django 3.2.7 on 2022-03-28 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('sales_invoice', models.TextField(verbose_name='Sales Invoice')),
                ('supplier', models.TextField(verbose_name='Supplier')),
                ('transaction_type', models.TextField(verbose_name='Transaction Type')),
                ('mrs_number', models.TextField(verbose_name='MRS')),
                ('requested_by', models.CharField(choices=[('1', 'In'), ('2', 'Out')], max_length=10, verbose_name='Tx Type')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'inventory',
                'verbose_name_plural': 'inventories',
                'db_table': 'inventory',
                'ordering': ['-trans_date'],
            },
        ),
        migrations.CreateModel(
            name='inventory_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(max_length=20, verbose_name='Inventory id')),
                ('brand', models.TextField(verbose_name='Brand')),
                ('item_description', models.TextField(verbose_name='Item description')),
                ('unit_measurement', models.TextField(verbose_name='Unit Measurement')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transactions_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.inventory')),
            ],
            options={
                'verbose_name': 'inventory_transaction',
                'verbose_name_plural': 'inventories_transactions',
                'db_table': 'inventory_transaction',
                'ordering': ['-transactions_inventory'],
            },
        ),
    ]
