# Generated by Django 3.2.7 on 2022-04-23 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_transaction',
            name='trans_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
