# Generated by Django 3.2.7 on 2022-03-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_inventory_inventory_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inventory',
            new_name='inventory_db',
        ),
        migrations.AlterModelTable(
            name='inventory_db',
            table='inventory_db',
        ),
    ]
