# Generated by Django 3.2.7 on 2022-03-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_auto_20220328_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_db',
            name='mrs_number',
            field=models.CharField(max_length=50, verbose_name='MRS'),
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='sales_invoice',
            field=models.CharField(max_length=50, verbose_name='Inventory id'),
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='supplier',
            field=models.CharField(max_length=100, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='inventory_db',
            name='transaction_type',
            field=models.CharField(choices=[('1', 'In'), ('2', 'Out')], max_length=10, verbose_name='Tx Type'),
        ),
        migrations.AlterField(
            model_name='inventory_transaction',
            name='item_description',
            field=models.CharField(max_length=100, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='inventory_transaction',
            name='unit_measurement',
            field=models.CharField(max_length=50, verbose_name='Unit'),
        ),
    ]
