# Generated by Django 3.2.7 on 2022-03-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_auto_20220328_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_transaction',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Brand'),
        ),
    ]
