# Generated by Django 3.2.7 on 2022-03-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_alter_inventory_transaction_brand'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory_db',
            table='inventory',
        ),
    ]
