# Generated by Django 3.2.7 on 2022-03-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0006_alter_inventory_db_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_db',
            name='requested_by',
            field=models.CharField(max_length=10, verbose_name='Requested by'),
        ),
    ]
